# Generated by Django 3.2.5 on 2022-03-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='busan_employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('job_metas', models.CharField(max_length=200)),
                ('apply', models.CharField(max_length=200)),
                ('edu', models.CharField(max_length=200)),
                ('emp_type', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('pay', models.CharField(max_length=200)),
            ],
        ),
    ]
